from flask import Blueprint, render_template, request, json

views = Blueprint('views', __name__)


@views.route('/')
def homepage():

	traject_options = [
		'Aachen (D) - Herzogenrath (D)',
		'Alkmaar',
		'Alkmaar - Uitgeest',
		'Almelo',
		'Almelo - Hengelo',
		'Almelo Dollegoor',
		'Almelo Gem. Stamlijn',
		'Alphen a/d Rijn',
		'Alphen a/d Rijn - Leiden Centraal',
		'Alphen a/d Rijn Industrieterrein Rijnhaven',
		'Amersfoort',
		'Amersfoort - Amersfoort Aansl.',
		'Amersfoort Aansl.',
		'Amersfoort Aansl. - Barneveld Noord',
		'Amersfoort Aansl. - Hattemerbroek',
		'Amersfoort Bokkeduinen',
		'Amersfoort Hoofdwerkplaats',
		'Amstelveen - Amsterdam Haarlemmermeer',
		'Amstelveen - Uithoorn',
		'Amsterdam - Vlissingen',
		'Amsterdam Bijlmer - Nieuwersluis-Loenen',
		'Amsterdam Bijlmer Arena',
		'Amsterdam Centraal',
		'Amsterdam Dijksgracht',
		'Amsterdam Hemhaven (gebied)',
		'Amsterdam Houtrakpolder (gebied)',
		'Amsterdam Lijnwerkplaats',
		'Amsterdam Muiderpoort',
		'Amsterdam Muiderpoort - Diemen',
		'Amsterdam Muiderpoort - Duivendrecht',
		'Amsterdam Riekerpolder',
		'Amsterdam Riekerpolder - Warmond',
		'Amsterdam Singelgracht Aansl.',
		'Amsterdam Sloterdijk',
		'Amsterdam Sloterdijk - Amsterdam Riekerpolder',
		'Amsterdam Sloterdijk - Haarlem',
		'Amsterdam Westhaven (gebied)',
		'Amsterdam Westhaven - Oldenzaal',
		'Apeldoorn',
		'Apeldoorn - Deventer',
		'Apeldoorn - Zutphen',
		'Arnhem',
		'Arnhem - Elst',
		'Arnhem - Velperbroek Aansl.',
		'Arnhem Gem. Stamlijn',
		'Arnhem Goederenstation - Velperbroek Aansl.',
		'Assen',
		'Assen - Haren',
		'Axel Axelse Vlakte',
		'Baarn',
		'Baarn - Amersfoort',
		'Barneveld Noord',
		'Barneveld Noord - Apeldoorn',
		'Barneveld Noord - Ede-Wageningen',
		'Beugen',
		'Beugen - Blerick',
		'Beverwijk Hoogovens - Roosendaal/Sloe',
		'Beverwijk Hoogovens - Zevenaar',
		'Beverwijk Hoogovens, Van Gelder',
		'Blauwkapel',
		'Blauwkapel - Den Dolder',
		'Blauwkapel - Lunetten',
		'Blerick',
		'Blerick - Eindhoven',
		'Born Franciscushaven',
		'Botlek',
		'Botlektunnel',
		'Boxtel',
		'Boxtel - Eindhoven',
		'Boxtel - Uden',
		'Breda',
		'Breda - Lage Zwaluwe',
		'Breda - Tilburg',
		'Breukelen',
		'Breukelen - Harmelen Aansl.',
		'Breukelen - Utrecht Centraal',
		'Budel Grens - Weert',
		'Budel Zinkfabriek',
		'CUP Valburg',
		'Coevorden - Coevorden Grens',
		'Coevorden Grens - Bentheim (D)',
		'Crailoo Bovenbouwwerkplaats',
		'De Haar Aansl.',
		'De Haar Aansl. - Ede-Wageningen',
		'Delden SERVO',
		'Delfzijl Stamlijn Havenschap',
		'Den Dolder',
		'Den Dolder - Amersfoort',
		'Den Dolder - Baarn',
		'Den Haag Binckhorst',
		'Den Haag Centraal',
		'Den Haag HS',
		'Den Haag HS - Schiedam Centrum',
		'Den Haag Laan van NOI',
		'Den Haag Mariahoeve',
		'Den Helder - Emmerich',
		'Den Helder - Heerhugowaard',
		'Deventer',
		'Deventer - Wierden',
		'Deventer - Zwolle',
		'Diemen',
		'Diemen - Duivendrecht',
		'Diemen Aansl.',
		'Diemen Aansl. - Weesp Aansl.',
		'Dieren',
		'Dieren - Apeldoorn',
		'Dieren - Zutphen',
		'Dordrecht',
		'Dordrecht - Rotterdam Barendrecht',
		'Dordrecht Industrieterrein Aansl. De Staart',
		'Dordrecht Zeehaventerrein',
		'Duivendrecht',
		'Duivendrecht - Amsterdam Riekerpolder',
		'Ede-Wageningen',
		'Ede-Wageningen - Arnhem',
		'Eijsden - Maastricht',
		'Eindhoven',
		'Eindhoven - Weert',
		'Elst',
		'Emmen - Weerdinge',
		'Emmen Emmtec',
		'Emmerich (D) - Zevenaar Grens',
		'Enschede - Amsterdam',
		'Enschede - Den Haag',
		'Enschede - Schiphol',
		'Etten-Leur Gem. Industrieterrein',
		'Geldermalsen',
		'Geldermalsen - Dordrecht',
		'Gent (B) - Zelzate (B)',
		'Gouda',
		'Gouda - Alphen a/d Rijn',
		'Gouda - Moordrecht Aansl.',
		'Gronau (D) - Enschede Grens',
		'Groningen',
		'Groningen - Drachten',
		'Groningen - Sauwerd',
		'Groningen Losplaats',
		'Groningen Losplaats - Waterhuizen Aansl.',
		'Groningen/Leeuwarden - Den Haag',
		'Groningen/Leeuwarden - Rotterdam',
		'Haarlem',
		'Haarlem - Santpoort Noord',
		'Haarlem - Warmond',
		'Haarlem - Zandvoort aan Zee',
		'Haarlem Goederenstation',
		'Haarlem Hoofdwerkplaats',
		'Haren',
		'Haren - Groningen Losplaats',
		'Haren - Waterhuizen Aansl.',
		'Harlingen Haven - Leeuwarden',
		'Harmelen Aansl.',
		'Harmelen Aansl. - Woerden',
		'Hattemerbroek',
		'Hazeldonk Grens - Noorderkempen (B)',
		'Heerenveen - Groningen',
		'Heerhugowaard',
		'Heerhugowaard - Alkmaar',
		'Heerhugowaard - Hoorn',
		'Heerlen',
		'Heerlen - Landgraaf',
		'Heerlen - Schin op Geul',
		'Hengelo',
		'Hengelo - Enschede Grens',
		'Hengelo - Hengelo Zoutindustrie',
		'Hengelo - Oldenzaal Grens',
		'Hengelo Akzo Zout Chemie',
		'Herfte Aansl.',
		'Herfte Aansl. - Mariënberg',
		'Herfte Aansl. - Meppel',
		'Herzogenrath (D)',
		'Hilversum',
		'Hilversum - Baarn',
		'Hilversum - Blauwkapel',
		'Hoorn',
		'Hoorn - Enkhuizen',
		'Hoorn - Medemblik',
		'Hulst Grens - Terneuzen Aansl.',
		'Kesteren - Geldermalsen',
		'Kijfhoek',
		'Kijfhoek - Lutterade DSM',
		'Kijfhoek - Meteren Aansl.',
		'Kijfhoek - Moerdijkbrug',
		'Kijfhoek - Oldenzaal',
		'Kijfhoek - Roosendaal/Sloe',
		'Kortsluitroute',
		'Lage Zwaluwe',
		'Lage Zwaluwe - Dordrecht',
		'Lage Zwaluwe - Roosendaal',
		'Lage Zwaluwe - s Hertogenbosch',
		'Lanaken (B) - Maastricht Grens',
		'Landgraaf',
		'Landgraaf - Haanrade Grens',
		'Landgraaf - Simpelveld',
		'Leeuwarden',
		'Leeuwarden - Groningen',
		'Leeuwarden - Stavoren',
		'Leiden Centraal',
		'Leiden Centraal - Den Haag Mariahoeve',
		'Leidschendam Lijnwerkplaats',
		'Lelystad Industrieterrein - Hattemerbroek',
		'Linne Grinderij',
		'Lunetten - De Haar Aansl.',
		'Lunetten - Geldermalsen',
		'Lunetten Aansl.',
		'Maastricht',
		'Maastricht - Maastricht Grens',
		'Maastricht - Sittard',
		'Maastricht Racc. Beatrixhaven',
		'Maasvlakte - Onnen',
		'Maasvlakte - Venlo',
		'Maasvlakte - Zevenaar',
		'Maasvlakte 2',
		'Mariënberg',
		'Mariënberg - Almelo',
		'Mariënberg - Emmen',
		'Meppel',
		'Meppel - Assen',
		'Meppel - Leeuwarden',
		'Meteren Aansl.',
		'Meteren Aansl. - Ressen-Bemmel',
		'Meteren Aansl. - s Hertogenbosch',
		'Moerdijk Industrieterrein',
		'Moordrecht Aansl.',
		'Moordrecht Aansl. - Den Haag Binckhorst',
		'Moordrecht Aansl. - Rotterdam Kleiweg',
		'Nederland',
		'Neerpelt (B) - Budel Grens',
		'Nieuw Amsterdam - Schoonebeek',
		'Nieuwersluis-Loenen',
		'Nieuwersluis-Loenen - Breukelen',
		'Nieuweschans Grens - Ihrhove (D)',
		'Nijmegen',
		'Nijmegen - Beugen',
		'Nijmegen Grens - Nijmegen',
		'Noordoost',
		'Nootdorp Aansl.',
		'Nootdorp Aansl. - Den Haag Laan van NOI',
		'Oldenzaal Grens - Bad Bentheim (D)',
		'Onnen Lijnwerkplaats',
		'Onnen Rangeerterrein',
		'Oosterhout Weststad',
		'Oss Racc. Elzenburg',
		'Pernis',
		'Prinsenbeek',
		'Prinsenbeek - Hazeldonk Grens',
		'Randstad Noord',
		'Randstad Zuid',
		'Ressen-Bemmel',
		'Ressen-Bemmel - Nijmegen',
		'Ressen-Bemmel - Zevenaar',
		'Rhenen - De Haar Aansl.',
		'Roermond',
		'Roermond - Venlo',
		'Roermond - Vlodrop Grens',
		'Roodeschool Eemshaven',
		'Roosendaal',
		'Roosendaal - Breda',
		'Roosendaal - Oldenzaal',
		'Roosendaal - Roosendaal Grens',
		'Roosendaal - Vlissingen',
		'Roosendaal Borchwerf',
		'Roosendaal Grens - Essen (B)',
		'Roosendaal Industrieterrein',
		'Rotterdam - Venlo',
		'Rotterdam Barendrecht',
		'Rotterdam Centraal',
		'Rotterdam Eemhaven',
		'Rotterdam Europoort 1',
		'Rotterdam Europoort 2',
		'Rotterdam Europoort 3',
		'Rotterdam Europoort 4',
		'Rotterdam Kleiweg',
		'Rotterdam Kleiweg - Nootdorp Aansl.',
		'Rotterdam Kleiweg - Rotterdam Westelijke Splitsing',
		'Rotterdam Lombardijen',
		'Rotterdam Lombardijen - Rotterdam Centraal',
		'Rotterdam Maasvlakte',
		'Rotterdam Rijn- en Maashaven',
		'Rotterdam Waalhaven Oost',
		'Rotterdam Westelijke Splitsing',
		'Rotterdam Westelijke Splitsing - Nieuw Vennep',
		'Rotterdam Zuid Goederen - Rotterdam Maasvlakte',
		'Santpoort Noord',
		'Santpoort Noord - IJmuiden',
		'Santpoort Noord - Uitgeest',
		'Sas van Gent Cerestar',
		'Sas van Gent Grens - Terneuzen Aansl.',
		'Sauwerd',
		'Sauwerd - Delfzijl',
		'Sauwerd - Winsum',
		'Schiedam Centrum',
		'Schiedam Centrum - Hoek van Holland Strand',
		'Schin op Geul',
		'Schin op Geul - Maastricht',
		'Simpelveld',
		'Simpelveld - Schin op Geul',
		'Simpelveld Grens - Simpelveld',
		'Sittard',
		'Sittard - Born',
		'Sittard - Heerlen',
		'Sittard - Roermond',
		'Sloe - Venlo',
		'Stadskanaal Hoofdstation - Musselkanaal-Valthermond',
		'Stadskanaal Hoofdstation - Zuidbroek',
		'Terneuzen Aansl.',
		'Terneuzen Aansl. - Terneuzen',
		'Terneuzen Dow Chemical',
		'Tiel Gem. Stamlijn',
		'Tilburg',
		'Tilburg - Boxtel',
		'Tilburg - Vught Aansl.',
		'Tilburg Hoofdwerkplaats',
		'Tilburg de Loven',
		'Uitgeest',
		'Uitgeest - Zaandam',
		'Uitgeest/Haarlem - Zevenaar',
		'Utrecht - Heerlen/Maastricht',
		'Utrecht Centraal',
		'Utrecht Centraal - Blauwkapel',
		'Utrecht Centraal - Harmelen Aansl.',
		'Utrecht Industrieterrein Lage Weide',
		'VAM-terrein Wijster',
		'Velperbroek Aansl.',
		'Velperbroek Aansl. - Dieren',
		'Velperbroek Aansl. - Zevenaar',
		'Venlo',
		'Venlo -Lutterade DSM',
		'Venlo Grens - Keulen (D)',
		'Venlo Grens - Venlo',
		'Venlo Tradeport',
		'Vetschau (D) - Simpelveld Grens',
		'Visé (B) - Eijsden Grens',
		'Vlissingen Sloehaven',
		'Vork',
		'Vork - Kesteren',
		'Vught Aansl.',
		'Vught Aansl. - Boxtel',
		'Warmond',
		'Warmond - Leiden Centraal',
		'Watergraafsmeer',
		'Waterhuizen Aansl.',
		'Waterhuizen Aansl. - Zuidbroek',
		'Weert',
		'Weert - Roermond',
		'Weesp Aansl.',
		'Weesp Aansl. - Hilversum',
		'Weesp Aansl. - Lelystad Industrieterrein',
		'Wierden',
		'Wierden - Almelo',
		'Winsum - Roodeschool',
		'Winterswijk',
		'Winterswijk - Zevenaar',
		'Woerden',
		'Woerden - Alphen a/d Rijn',
		'Woerden - Gouda',
		'Woudenberg-Scherpenzeel - Amersfoort',
		'Zaandam',
		'Zaandam - Amsterdam Singelgracht Aansl.',
		'Zaandam - Amsterdam Sloterdijk',
		'Zaandam - Hoorn',
		'Zelzate (B) - Sas van Gent Grens',
		'Zevenaar',
		'Zevenaar - Zevenaar Grens',
		'Zuid',
		'Zuidbroek',
		'Zuidbroek - Nieuweschans Grens',
		'Zutphen',
		'Zutphen - Deventer',
		'Zutphen - Hengelo',
		'Zutphen - Winterswijk',
		'Zwijndrecht Groote Lindt',
		'Zwolle',
		'Zwolle - Herfte Aansl.',
		'Zwolle - Kampen',
		'Zwolle - Roosendaal',
		'Zwolle - Wierden',
		'Zwolle Industrieterrein Katwolde',
		'Zwolle Lijnwerkplaats',
		'Zwolle Rangeerterrein',
		's Hertogenbosch',
		's Hertogenbosch - Nijmegen',
		's Hertogenbosch - Vught Aansl.',
		's Hertogenbosch Gem. Stamlijn'
	]

	return render_template('index.html', traject_options=traject_options)


@views.route('/', methods=['POST'])
def result():
	test1 = request.form['test1']
	test2 = request.form['test2']
	return json.dumps({'status': 'OK', 'test1': test1, 'test2': test2})
